### ISSUE TITLE
Tea Cozy Files (Read First)

### ISSUE THREAD

**Issue by griffinlacek** [Skprose/excursion#1]
There are numerous files for index.html and style.css scattered over the project folder. I'm not sure if you're saving changes, but saving as different files, but generally we just want to save one of each file over and over again. We can then use git to save the "state" of that file so we can go back and see what changes we made to it over time.

Because I don't know which file is your final one I'm going to pick index8.html and style8.css

In the future though, remember to just save one version of files over and over and use git as a tool to track changes!

**Comment by Skprose** [comment]
Sorry about it. I had issues with setting git. It was not working. I had to change configuration and install some file to finally get Git command working for me. So in the mean while ended up creating so many versions. Index8 and style8 - are the latest files for review. Thanks a lot!
