### ISSUE TITLE
HTML Indentation

### ISSUE THREAD

**Issue by griffinlacek** [Skprose/excursion#3]
Indentation is just for developers use, but good indentation will make reviewing and working on your code much easier. Throughout your HTML there are small mis-indents. Generally you have the parent-child indent throughout your code so that's really good! Just make sure to keep an eye out for mis-indented areas!

`<body>` should be indented here
https://github.com/Skprose/excursion/blob/master/cdprojects/TeaCozy/index8.html#L7-L8

Opening div isn't indented equal to closing div
https://github.com/Skprose/excursion/blob/master/cdprojects/TeaCozy/index8.html#L66-L89

Closing div isn't indented equal to opening div
https://github.com/Skprose/excursion/blob/master/cdprojects/TeaCozy/index8.html#L93-L102

**Comment by Skprose** [comment]
Opening - I think I closed one of the div in the same line, that caused confusion. Will maintain uniformity.
Closing - div's i commented some of the lines.
Will concentrate more on indentation.
