### ISSUE TITLE
Using <br /> in HTML

### ISSUE THREAD

**Issue by griffinlacek** [Skprose/excursion#4]
There's nothing wrong with using `<br />` in your HTML, but when it's just used to add space between elements we can instead use CSS styles like margin or padding to add that space without creating extra HTML elements. It's generally considered a cleaner, more efficient way of adding space!

https://github.com/Skprose/excursion/blob/master/cdprojects/TeaCozy/index8.html#L23-L26`

**Comment by Skprose** [comment]
I was using <br /> from initial stages of this course, just kept continuing.Will try to avoid and use CSS style. Thanks.
