### ISSUE TITLE
Body margin causes space around page (noticeably the header)

### ISSUE THREAD

**Issue by griffinlacek** [Skprose/excursion#5]
There is a space between your header (all the page really) and the window that exists in Chrome (and possibly other browsers) because a margin is applied to body if we don't explicitly set margin to 0. So, in body we want to set margin: 0 to counteract that problem!

We want to target body here instead of using *. Both work, but * leads to some unintended side-effects because it targets every single element instead of just valid children elements of body.

https://github.com/Skprose/excursion/blob/master/cdprojects/TeaCozy/Resources/style8.css#L1-L7

**Comment by Skprose** [comment]
Yes, Noticed while running the script but didn't know why. Thanks a lot!
