### ISSUE TITLE
Unneeded <p> wrapping <div>

### ISSUE THREAD

**Issue by griffinlacek** [Skprose/excursion#7]
You have a p class "missioncenter" wrapping a div, which is generally fine, but not really needed since the div will act as a container. What we can do is remove the missioncenter p and set a margin-top to the div (maybe set this as the new missioncenter) to push the mission text down.

https://github.com/Skprose/excursion/blob/master/cdprojects/TeaCozy/index8.html#L21-L28

**Comment by Skprose** [comment]
Yeah, should have done in that way.
